name: test
on: [push, pull_request]
env:
  GO111MODULE: auto
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p ~/go/src/github.com/hjson
          cd ..
          cp -r hjson-go ~/go/src/github.com/hjson/
      - run: go version
      - run: go test -v
      - run: |
          cd ~/go/src/github.com/hjson/hjson-go/hjson-cli
          go install -i
