name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: go version
      - run: go test -v
      - run: |
          cd hjson-cli
          go install -i

  build_hjson-cli_releases:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build the hjson-cli binaries
        run: ./build_release.sh
